# Projeto 8 - Inteligência Financeira - Prevendo Preços de Ativos em Tempo Real

### Objetivo do Projeto: 
<p>Criar uma aplicação que possa fazer analise de ativos financeiros e gerar previsões em tempo real

In [ ]:
# Instalando o pacote yfinance que é um pacote oficial do Yahoo Finance para baixar dados atualizados de ações
#!pip install yfinance

# Instalando o pacote ta (Technical Analysis) que é um pacote onde podemos utilizar as funções prontas para calcular indicadores financeiros de ações
#!pip install ta

# Site do Yahoo Finance para ver as empresas e nomes de ativos
# https://finance.yahoo.com/markets/stocks/most-active/

In [1]:
! pip install yfinance

Collecting yfinance
  Downloading yfinance-1.5.2-py2.py3-none-any.whl (144 kB)
     ---------------------------------------- 0.0/144.1 kB ? eta -:--:--
     -------- ------------------------------ 30.7/144.1 kB 1.3 MB/s eta 0:00:01
     ------------------------ -------------- 92.2/144.1 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 144.1/144.1 kB 1.2 MB/s eta 0:00:00
Collecting curl_cffi>=0.15
  Downloading curl_cffi-0.16.0-cp310-abi3-win_amd64.whl (2.0 MB)
     ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
     --- ------------------------------------ 0.2/2.0 MB 9.6 MB/s eta 0:00:01
     -------- ------------------------------- 0.4/2.0 MB 6.3 MB/s eta 0:00:01
     ------------------ --------------------- 0.9/2.0 MB 7.3 MB/s eta 0:00:01
     ---------------------------------------  1.9/2.0 MB 11.3 MB/s eta 0:00:01
     ---------------------------------------- 2.0/2.0 MB 10.5 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.11.1
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
     ---------------------------------------- 0.0/109.9 kB ? eta -:--:--
     ---------------------------------------- 109.9/109.9 kB ? eta 0:00:00
Collecting websockets>=13.0
  Downloading websockets-16.1.1-cp310-cp310-win_amd64.whl (180 kB)
     ---------------------------------------- 0.0/180.2 kB ? eta -:--:--
     ------------------------------------- 180.2/180.2 kB 10.6 MB/s eta 0:00:00
Collecting pandas>=1.3.0
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Collecting requests>=2.31
  Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Collecting multitasking>=0.0.7
  Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Collecting peewee>=3.16.2
  Downloading peewee-4.3.0-py3-none-any.whl (179 kB)
     ---------------------------------------- 0.0/179.5 kB ? eta -:--:--
     ------------------------------------- 179.5/179.5 kB 10.6 MB/s eta 0:00:00
Collecting numpy>=1.16.5
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting protobuf>=3.19.0
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from yfinance) (4.11.2)
Collecting pytz>=2022.5
  Using cached pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Collecting soupsieve>=1.6.1
  Downloading soupsieve-2.9.2-py3-none-any.whl (37 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Collecting cffi>=2.0.0
  Downloading cffi-2.1.1-cp310-cp310-win_amd64.whl (185 kB)
     ---------------------------------------- 0.0/185.1 kB ? eta -:--:--
     ---------------------------------------- 185.1/185.1 kB ? eta 0:00:00
Collecting certifi>=2024.2.2
  Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Collecting charset_normalizer<4,>=2
  Using cached charset_normalizer-3.4.9-cp310-cp310-win_amd64.whl (162 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.18-py3-none-any.whl (65 kB)
Collecting urllib3<3,>=1.26
  Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Collecting pycparser
  Downloading pycparser-3.0-py3-none-any.whl (48 kB)
     ---------------------------------------- 0.0/48.2 kB ? eta -:--:--
     ---------------------------------------- 48.2/48.2 kB ? eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Installing collected packages: pytz, multitasking, websockets, urllib3, tzdata, soupsieve, pycparser, protobuf, peewee, numpy, idna, charset_normalizer, certifi, requests, pandas, cffi, beautifulsoup4, curl_cffi, yfinance
Successfully installed beautifulsoup4-4.15.0 certifi-2026.7.22 cffi-2.1.1 charset_normalizer-3.4.9 curl_cffi-0.16.0 idna-3.18 multitasking-0.0.13 numpy-2.2.6 pandas-2.3.3 peewee-4.3.0 protobuf-7.35.1 pycparser-3.0 pytz-2026.3.post1 requests-2.34.2 soupsieve-2.9.2 tzdata-2026.3 urllib3-2.7.0 websockets-16.1.1 yfinance-1.5.2

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
! pip install ta

Collecting ta
  Downloading ta-0.11.0.tar.gz (25 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from ta) (2.2.6)
Requirement already satisfied: pandas in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from ta) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from pandas->ta) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from pandas->ta) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from pandas->ta) (2026.3)
Requirement already satisfied: six>=1.5 in c:\users\gabri\projetos\applicationfinancialanalysis\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->ta) (1.17.0)
Installing collected packages: ta
  Running setup.py install for ta: started
  Running setup.py install for ta: finished with status 'done'
Successfully installed ta-0.11.0

  DEPRECATION: ta is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import datetime
import pandas as pd
#import streamlit as st
import yfinance as yf
from datetime import date
from ta.momentum import RSIIndicator
from ta.volatility import BollingerBands
from ta.trend import MACD, EMAIndicator, SMAIndicator
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [2]:
# Criando uma função para baixar os dados de ativos
def download_dados(ticker, start_date, end_date):
    
    ativo = yf.Ticker(ticker)
    df = ativo.history(start=start_date, end=end_date)

    # Retorna o DataFrame com os dados baixados
    return df

In [3]:
# Definindo os parametros
num_pontos_dados = 720
today = datetime.date.today()
start_date = today - datetime.timedelta(days = num_pontos_dados)
end_date = today
stock = 'GOOG'

In [4]:
# Visualizando os valores dos parametros
print(num_pontos_dados)
print(today)
print(start_date)
print(end_date)
print(stock)

720
2026-08-12
2024-08-22
2026-08-12
GOOG

In [5]:
# Executando função que ira baixar os dados da api
df_dados = download_dados(stock,start_date,end_date)
df_dados.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-22 00:00:00-04:00,167.753329,168.130441,163.773857,164.230362,19123800,0.0,0.0
2024-08-23 00:00:00-04:00,165.282287,166.671625,164.399062,166.155579,14281600,0.0,0.0
2024-08-26 00:00:00-04:00,166.875073,168.090754,165.054048,166.651779,11990300,0.0,0.0
2024-08-27 00:00:00-04:00,166.334189,166.964350,164.895229,165.113556,13718200,0.0,0.0
2024-08-28 00:00:00-04:00,165.510508,166.115865,162.037149,163.247864,15208700,0.0,0.0

In [6]:
# Calcula as Bandas de Bollinger para o preço de fechamento
indicador_bb = BollingerBands(df_dados.Close)
indicador_bb.bollinger_hband()

Date
2024-08-22 00:00:00-04:00           NaN
2024-08-23 00:00:00-04:00           NaN
2024-08-26 00:00:00-04:00           NaN
2024-08-27 00:00:00-04:00           NaN
2024-08-28 00:00:00-04:00           NaN
                                ...
2026-08-05 00:00:00-04:00    380.005147
2026-08-06 00:00:00-04:00    380.044178
2026-08-07 00:00:00-04:00    379.904848
2026-08-10 00:00:00-04:00    380.331277
2026-08-11 00:00:00-04:00    379.404842
Name: hband, Length: 493, dtype: float64

In [7]:
# Faz uma cópia do DataFrame
df_bb = df_dados
df_bb.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-08-22 00:00:00-04:00,167.753329,168.130441,163.773857,164.230362,19123800,0.0,0.0
2024-08-23 00:00:00-04:00,165.282287,166.671625,164.399062,166.155579,14281600,0.0,0.0
2024-08-26 00:00:00-04:00,166.875073,168.090754,165.054048,166.651779,11990300,0.0,0.0
2024-08-27 00:00:00-04:00,166.334189,166.964350,164.895229,165.113556,13718200,0.0,0.0
2024-08-28 00:00:00-04:00,165.510508,166.115865,162.037149,163.247864,15208700,0.0,0.0

In [10]:
# Insere uma boluna com o valor da banda de bolinger
df_bb['bb_maximo'] = indicador_bb.bollinger_hband()
df_bb.head(30)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,bb_minimo,bb_maximo
Date,,,,,,,,,
2024-08-22 00:00:00-04:00,167.753329,168.130441,163.773857,164.230362,19123800,0.0,0.0,NaN,NaN
2024-08-23 00:00:00-04:00,165.282287,166.671625,164.399062,166.155579,14281600,0.0,0.0,NaN,NaN
2024-08-26 00:00:00-04:00,166.875073,168.090754,165.054048,166.651779,11990300,0.0,0.0,NaN,NaN
2024-08-27 00:00:00-04:00,166.334189,166.964350,164.895229,165.113556,13718200,0.0,0.0,NaN,NaN
2024-08-28 00:00:00-04:00,165.510508,166.115865,162.037149,163.247864,15208700,0.0,0.0,NaN,NaN
2024-08-29 00:00:00-04:00,164.796007,166.354064,160.749044,162.156250,17133800,0.0,0.0,NaN,NaN
2024-08-30 00:00:00-04:00,162.970016,164.021945,162.166184,163.853241,18498800,0.0,0.0,NaN,NaN
2024-09-03 00:00:00-04:00,162.071930,162.136438,156.653482,157.402740,26533100,0.0,0.0,NaN,NaN
2024-09-04 00:00:00-04:00,156.871793,159.179093,156.241632,156.608810,17410700,0.0,0.0,NaN,NaN
2024-09-05 00:00:00-04:00,156.579056,159.789434,156.321041,157.392822,14139500,0.0,0.0,NaN,NaN
2024-09-06 00:00:00-04:00,157.482111,158.008076,150.778523,150.972046,24999100,0.0,0.0,NaN,NaN
2024-09-09 00:00:00-04:00,152.661314,153.664940,147.265544,148.597092,28057700,0.2,0.0,NaN,NaN
2024-09-10 00:00:00-04:00,150.495055,151.339702,148.600082,149.064133,20401800,0.0,0.0,NaN,NaN
2024-09-11 00:00:00-04:00,150.137345,151.518580,147.762415,151.190659,18991500,0.0,0.0,NaN,NaN
2024-09-12 00:00:00-04:00,153.833872,154.628831,152.532135,154.559265,20980800,0.0,0.0,NaN,NaN
2024-09-13 00:00:00-04:00,155.376080,158.270707,155.125670,157.371414,16733900,0.0,0.0,NaN,NaN
2024-09-16 00:00:00-04:00,157.331691,158.235957,156.616230,157.987534,14157600,0.0,0.0,NaN,NaN
2024-09-17 00:00:00-04:00,159.080589,160.571132,158.404884,159.269394,12064800,0.0,0.0,NaN,NaN
2024-09-18 00:00:00-04:00,159.835792,160.610873,158.653293,159.796036,16756500,0.0,0.0,NaN,NaN
2024-09-19 00:00:00-04:00,163.780748,163.949674,161.497234,162.210709,17548200,0.0,0.0,147.720857,169.662272
2024-09-20 00:00:00-04:00,163.482675,163.711220,162.151112,163.601913,46362700,0.0,0.0,147.749637,169.570647
2024-09-23 00:00:00-04:00,164.297470,165.559466,161.922540,162.041794,15648400,0.0,0.0,147.970146,168.938759
2024-09-24 00:00:00-04:00,163.214354,163.512466,161.008351,162.608200,18774100,0.0,0.0,148.263847,168.240701
2024-09-25 00:00:00-04:00,161.942433,163.181564,161.748655,161.962311,13607900,0.0,0.0,148.450708,167.738715
2024-09-26 00:00:00-04:00,163.989428,164.456465,162.469076,162.796997,18234500,0.0,0.0,148.474456,167.669880
2024-09-27 00:00:00-04:00,162.876514,165.917218,162.797017,164.247803,13604300,0.0,0.0,148.360225,167.993266
2024-09-30 00:00:00-04:00,163.741011,166.304745,163.601894,166.135818,14070100,0.0,0.0,148.164828,168.416921
2024-10-01 00:00:00-04:00,167.795276,169.365315,164.853933,167.358047,18629500,0.0,0.0,147.933654,169.643625
2024-10-02 00:00:00-04:00,166.702210,167.815159,165.201737,166.255051,12745000,0.0,0.0,147.997118,170.544786
2024-10-03 00:00:00-04:00,164.774466,166.851284,164.327291,166.155701,11004300,0.0,0.0,148.085588,171.332604

In [11]:
df_bb['bb_minimo'] = indicador_bb.bollinger_lband()
df_bb.head(30)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,bb_minimo,bb_maximo
Date,,,,,,,,,
2024-08-22 00:00:00-04:00,167.753329,168.130441,163.773857,164.230362,19123800,0.0,0.0,NaN,NaN
2024-08-23 00:00:00-04:00,165.282287,166.671625,164.399062,166.155579,14281600,0.0,0.0,NaN,NaN
2024-08-26 00:00:00-04:00,166.875073,168.090754,165.054048,166.651779,11990300,0.0,0.0,NaN,NaN
2024-08-27 00:00:00-04:00,166.334189,166.964350,164.895229,165.113556,13718200,0.0,0.0,NaN,NaN
2024-08-28 00:00:00-04:00,165.510508,166.115865,162.037149,163.247864,15208700,0.0,0.0,NaN,NaN
2024-08-29 00:00:00-04:00,164.796007,166.354064,160.749044,162.156250,17133800,0.0,0.0,NaN,NaN
2024-08-30 00:00:00-04:00,162.970016,164.021945,162.166184,163.853241,18498800,0.0,0.0,NaN,NaN
2024-09-03 00:00:00-04:00,162.071930,162.136438,156.653482,157.402740,26533100,0.0,0.0,NaN,NaN
2024-09-04 00:00:00-04:00,156.871793,159.179093,156.241632,156.608810,17410700,0.0,0.0,NaN,NaN
2024-09-05 00:00:00-04:00,156.579056,159.789434,156.321041,157.392822,14139500,0.0,0.0,NaN,NaN
2024-09-06 00:00:00-04:00,157.482111,158.008076,150.778523,150.972046,24999100,0.0,0.0,NaN,NaN
2024-09-09 00:00:00-04:00,152.661314,153.664940,147.265544,148.597092,28057700,0.2,0.0,NaN,NaN
2024-09-10 00:00:00-04:00,150.495055,151.339702,148.600082,149.064133,20401800,0.0,0.0,NaN,NaN
2024-09-11 00:00:00-04:00,150.137345,151.518580,147.762415,151.190659,18991500,0.0,0.0,NaN,NaN
2024-09-12 00:00:00-04:00,153.833872,154.628831,152.532135,154.559265,20980800,0.0,0.0,NaN,NaN
2024-09-13 00:00:00-04:00,155.376080,158.270707,155.125670,157.371414,16733900,0.0,0.0,NaN,NaN
2024-09-16 00:00:00-04:00,157.331691,158.235957,156.616230,157.987534,14157600,0.0,0.0,NaN,NaN
2024-09-17 00:00:00-04:00,159.080589,160.571132,158.404884,159.269394,12064800,0.0,0.0,NaN,NaN
2024-09-18 00:00:00-04:00,159.835792,160.610873,158.653293,159.796036,16756500,0.0,0.0,NaN,NaN
2024-09-19 00:00:00-04:00,163.780748,163.949674,161.497234,162.210709,17548200,0.0,0.0,147.720857,169.662272
2024-09-20 00:00:00-04:00,163.482675,163.711220,162.151112,163.601913,46362700,0.0,0.0,147.749637,169.570647
2024-09-23 00:00:00-04:00,164.297470,165.559466,161.922540,162.041794,15648400,0.0,0.0,147.970146,168.938759
2024-09-24 00:00:00-04:00,163.214354,163.512466,161.008351,162.608200,18774100,0.0,0.0,148.263847,168.240701
2024-09-25 00:00:00-04:00,161.942433,163.181564,161.748655,161.962311,13607900,0.0,0.0,148.450708,167.738715
2024-09-26 00:00:00-04:00,163.989428,164.456465,162.469076,162.796997,18234500,0.0,0.0,148.474456,167.669880
2024-09-27 00:00:00-04:00,162.876514,165.917218,162.797017,164.247803,13604300,0.0,0.0,148.360225,167.993266
2024-09-30 00:00:00-04:00,163.741011,166.304745,163.601894,166.135818,14070100,0.0,0.0,148.164828,168.416921
2024-10-01 00:00:00-04:00,167.795276,169.365315,164.853933,167.358047,18629500,0.0,0.0,147.933654,169.643625
2024-10-02 00:00:00-04:00,166.702210,167.815159,165.201737,166.255051,12745000,0.0,0.0,147.997118,170.544786
2024-10-03 00:00:00-04:00,164.774466,166.851284,164.327291,166.155701,11004300,0.0,0.0,148.085588,171.332604

In [12]:
# Seleciona apenas as colunas relevantes para exibição
df_bb = df_bb[['Close', 'bb_maximo', 'bb_minimo']]
df_bb.head(30)

                                Close   bb_maximo   bb_minimo
Date
2024-08-22 00:00:00-04:00  164.230362         NaN         NaN
2024-08-23 00:00:00-04:00  166.155579         NaN         NaN
2024-08-26 00:00:00-04:00  166.651779         NaN         NaN
2024-08-27 00:00:00-04:00  165.113556         NaN         NaN
2024-08-28 00:00:00-04:00  163.247864         NaN         NaN
2024-08-29 00:00:00-04:00  162.156250         NaN         NaN
2024-08-30 00:00:00-04:00  163.853241         NaN         NaN
2024-09-03 00:00:00-04:00  157.402740         NaN         NaN
2024-09-04 00:00:00-04:00  156.608810         NaN         NaN
2024-09-05 00:00:00-04:00  157.392822         NaN         NaN
2024-09-06 00:00:00-04:00  150.972046         NaN         NaN
2024-09-09 00:00:00-04:00  148.597092         NaN         NaN
2024-09-10 00:00:00-04:00  149.064133         NaN         NaN
2024-09-11 00:00:00-04:00  151.190659         NaN         NaN
2024-09-12 00:00:00-04:00  154.559265         NaN         NaN
2024-09-13 00:00:00-04:00  157.371414         NaN         NaN
2024-09-16 00:00:00-04:00  157.987534         NaN         NaN
2024-09-17 00:00:00-04:00  159.269394         NaN         NaN
2024-09-18 00:00:00-04:00  159.796036         NaN         NaN
2024-09-19 00:00:00-04:00  162.210709  169.662272  147.720857
2024-09-20 00:00:00-04:00  163.601913  169.570647  147.749637
2024-09-23 00:00:00-04:00  162.041794  168.938759  147.970146
2024-09-24 00:00:00-04:00  162.608200  168.240701  148.263847
2024-09-25 00:00:00-04:00  161.962311  167.738715  148.450708
2024-09-26 00:00:00-04:00  162.796997  167.669880  148.474456
2024-09-27 00:00:00-04:00  164.247803  167.993266  148.360225
2024-09-30 00:00:00-04:00  166.135818  168.416921  148.164828
2024-10-01 00:00:00-04:00  167.358047  169.643625  147.933654
2024-10-02 00:00:00-04:00  166.255051  170.544786  147.997118
2024-10-03 00:00:00-04:00  166.155701  171.332604  148.085588

In [13]:
# Calcula o objeto MACD para o preço de fechamento
macd_object = MACD(df_dados['Close'])
macd_object.macd()

Date
2024-08-22 00:00:00-04:00         NaN
2024-08-23 00:00:00-04:00         NaN
2024-08-26 00:00:00-04:00         NaN
2024-08-27 00:00:00-04:00         NaN
2024-08-28 00:00:00-04:00         NaN
                               ...
2026-08-05 00:00:00-04:00    0.784210
2026-08-06 00:00:00-04:00    1.123895
2026-08-07 00:00:00-04:00    1.125940
2026-08-10 00:00:00-04:00    1.303770
2026-08-11 00:00:00-04:00    0.403965
Name: MACD_12_26, Length: 493, dtype: float64

In [14]:
# Calcula o indicador RSI para o preço de fechamento
rsi = RSIIndicator(df_dados.Close).rsi()
rsi

Date
2024-08-22 00:00:00-04:00          NaN
2024-08-23 00:00:00-04:00          NaN
2024-08-26 00:00:00-04:00          NaN
2024-08-27 00:00:00-04:00          NaN
2024-08-28 00:00:00-04:00          NaN
                               ...
2026-08-05 00:00:00-04:00    54.265051
2026-08-06 00:00:00-04:00    52.550753
2026-08-07 00:00:00-04:00    50.993821
2026-08-10 00:00:00-04:00    52.142666
2026-08-11 00:00:00-04:00    45.868862
Name: rsi, Length: 493, dtype: float64

In [15]:
# Calcula a Média Móvel Simples (SMA) para o preço de fechamento
sma = SMAIndicator(df_dados.Close, window=14).sma_indicator()
sma

Date
2024-08-22 00:00:00-04:00           NaN
2024-08-23 00:00:00-04:00           NaN
2024-08-26 00:00:00-04:00           NaN
2024-08-27 00:00:00-04:00           NaN
2024-08-28 00:00:00-04:00           NaN
                                ...
2026-08-05 00:00:00-04:00    344.016429
2026-08-06 00:00:00-04:00    344.766429
2026-08-07 00:00:00-04:00    344.916430
2026-08-10 00:00:00-04:00    345.605715
2026-08-11 00:00:00-04:00    345.683572
Name: sma_14, Length: 493, dtype: float64

In [16]:
# Calcula a Média Móvel Exponencial (EMA) para o preço de fechamento
ema = EMAIndicator(df_dados.Close).ema_indicator()
ema

Date
2024-08-22 00:00:00-04:00           NaN
2024-08-23 00:00:00-04:00           NaN
2024-08-26 00:00:00-04:00           NaN
2024-08-27 00:00:00-04:00           NaN
2024-08-28 00:00:00-04:00           NaN
                                ...
2026-08-05 00:00:00-04:00    350.936083
2026-08-06 00:00:00-04:00    351.693938
2026-08-07 00:00:00-04:00    351.930747
2026-08-10 00:00:00-04:00    352.451980
2026-08-11 00:00:00-04:00    351.191716
Name: ema_14, Length: 493, dtype: float64